CREATE TABLE IF NOT EXISTS comments (
	id TEXT PRIMARY KEY NOT NULL,
	postId TEXT NOT NULL,
	parent_comment_id TEXT NULL DEFAULT(NULL),
	content TEXT NOT NULL,
	like INTEGER DEFAULT(0) NOT NULL,
	dislike INTEGER DEFAULT(0) NOT NULL,
	created_at TEXT DEFAULT(DATETIME()) NOT NULL,
	updated_at TEXT DEFAULT(DATETIME()) NOT NULL,
	FOREIGN KEY(postId) REFERENCES posts(id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(parent_comment_id) REFERENCES comments(id) ON UPDATE CASCADE ON DELETE CASCADE
);