CREATE TABLE IF NOT EXISTS posts (
id TEXT PRIMARY KEY NOT NULL,
content TEXT NOT NULL,
like INTEGER DEFAULT(0) NOT NULL,
dislike INTEGER DEFAULT(0) NOT NULL,
amount_comments INTEGER DEFAULT(0) NOT NULL,
created_at TEXT DEFAULT(DATETIME()) NOT NULL,
updated_at TEXT DEFAULT(DATETIME()) NOT NULL
);